### ISSUE TITLE
No longer working in part 2?

### ISSUE THREAD

**Issue by rgerr444** [SilentNightSound/HI-Model-Importer#2]
![image](https://github.com/user-attachments/assets/b1cecbbf-9f02-4b50-b5bc-65cca75c7686)

I'm not sure if this is a me issue or maybe something is wrong but I can't even export an untouched dump to a mod correctly, I didn't edit anything on the model dunno if the dump is the issue either I used this command 
py honkai_3dmigoto_collect.py -n "Vita" -vb 26df1cf4 4f620823 -c "Hair" "Body" --is_part2 --remove_sanity --has_normalmap

**Comment by leotorrez** [comment]
The script was never tested on part 2 characters- it was written before their announcement even. Try GUI Colllect https://github.com/Petrascyll/gui_collect

**Comment by rgerr444** [comment]
Oh actually? I assumed it did reading the commit logs that says it added support for them but makes sense if it wasn't tested 
![image](https://github.com/user-attachments/assets/c00023b0-a42f-477f-bc0f-69e94a45fe35)
sadly GUI Collect gave similar results but weirdly unlike before the hair is completely fine and the body looks slightly better
I know HI3 modding isn't as invested into or relevant so I don't expect a fix to come out fast if even at all but it would be nice to know if there was one

**Comment by leotorrez** [comment]
it was lightly tested and things broke after that commit.... I will try and revise this on the next game update. I honestly can't be bothered to update yet xD

**Comment by rgerr444** [comment]
Take all the time you need I'm very grateful! Thank you for your time!

**Comment by leotorrez** [comment]
after testing for some days- its fineeee when collecting dumps i recoomend using GUI collect. Is the simplest most up to date tool for the job https://github.com/Petrascyll/gui_collect
